name: Mover
version: 1.0
author: KamikazePlatypus
main: com.kamikazedev.mover.Mover

commands:
  mover:
    description: Creates a block animation
    usage: /mover {velocity} {time} [acceleration] [block1] [block2]
  test:
    description: Spawns a movable armor stand
    usages: /test